services:
  - type: web
    name: healthcare-chatbot
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: USE_REDIS
        value: "false"

      - key: WHATSAPP_PROVIDER
        value: AUTOBOTCHAT
      - key: AUTOBOTCHAT_USERNAME
        value: Amplrhealth
      - key: META_VERIFY_TOKEN
        value: amplrhealth_webhook_token
      - key: BOT_PHONE_NUMBER
        value: "919849649049"
      - key: ADMIN_PHONE
        value: "919849649049"
      - key: ADMIN_EMAIL
        value: "amplrhealth@gmail.com"
      - key: AUTOBOTCHAT_JWT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false




